#
# datasource config
#

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: swmind1234

#mybatis.config-location: classpath:mybatis-config.xml
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
#spring.datasource.schema=classpath:import.sql
mybatis.mapper-locations: classpath*:**/mappers/*.xml

